# Generated by Django 5.0.1 on 2024-01-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_todoitem_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
